POST https://api.themoviedb.org/3/list?api_key=d5e44dd33260c00852e5fd0e20c58722&session_id=aa705ed7c9f86dd8bd7ae29d949b3ec53dee320c
Content-Type: application/json

{
  "name": "This is my awesome test list.",
  "description": "Just an awesome list dawg.",
  "language": "en"
}